name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    name: Compile resume pdf
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Sync with remote
        run: |
          git checkout main
          git pull --rebase

      - name: Install poppler-utils
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: thomasweise/docker-texlive-full:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd data
            make clean
            make all
            
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Apply pdflatex changes"
          commit_author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
